import { I18nProviderClient } from '../../locales/client';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <main className='flex min-h-screen flex-col items-center bg-background'>
          <I18nProviderClient>
            {children}
          </I18nProviderClient>
        </main>
      </body>
    </html>
  );
}
